version: '3.7'
services:
  service:
    container_name: frame
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000
    env_file:
      - .envs/.env.dev
    ports:
      - "127.0.0.1:8000:8000"
    volumes:
      - ./src:/app
